# Generated by Django 4.0.1 on 2022-01-18 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repuestos',
            old_name='numero_respuesto',
            new_name='numero_repuesto',
        ),
    ]
