# Generated by Django 4.0.1 on 2022-01-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_rename_numero_respuesto_repuestos_numero_repuesto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregas',
            name='entregado',
        ),
        migrations.AddField(
            model_name='entregas',
            name='repuesto',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
